### ISSUE TITLE
Unable to Close TCP Client Connection

### ISSUE THREAD

**Issue by DBTaylor** [slowtec/tokio-modbus#33]
Target: ARMv7 (musl)

I have a warp webserver that upon a request will open a connection and read some registers, and I want the connection to close after the registers are successfully read. Using the async API, I expected the TCP client connections to close when contexts are dropped, but they do not (netstat shows them in established state). I tried Context::disconnect, but that causes a panic ('internal error: entered unreachable code'). What is the correct way to disconnect the TCP connection?

```rust
let read_input_registers = get2()
        .and(path!("rir" / u16 / u16)
        .and(path::end())
        .and_then(move |start, count|{
            let (p, c) = futures::sync::oneshot::channel::<String>();
            remote.spawn(move |handle|
                client::tcp::connect(handle, localhost)
                .and_then(move |ctx| ctx.read_input_registers(start, count)/*.and_then(move |res| ctx.disconnect().then(|_| Ok(res)))*/)
                .then(|res|{
                    p.send(match res{
                        Ok(data) => format!("{:?}", data),
                        Err(err) =>  format!("{:?}", err)
                    }).unwrap_or(());
                    Ok(())
                })
            );
            c.map_err(|err| warp::reject::custom(err))
        }));
```
I've switched to the modbus crate until I can figure this out. I'd prefer to use this one since it's non-blocking.

**Comment by flosse** [comment]
@DBTaylor Thanks for your feedback.
We'll try to reproduce this soon.
Probably this issue is related to the outdated `tokio-proto` crate (see #18).
The next version of tokio-modbus will definitely get rid of it and will use the new async/await features of Rust. So if you're interested to help feel free to contact us :)

**Comment by flosse** [comment]
@uklotzde If you're bored: can you have a look at this?

**Comment by DBTaylor** [comment]
@flosse Thanks for the quick response. Monday I'll put together a minimal program that reproduces this - I'll also check it on a Tier 1 target to make sure it's not a target specific issue. Glad to hear async/await support is coming - way easier to read than future combinators. I would totally help if I had any idea what I was doing.

**Comment by DBTaylor** [comment]
@flosse here is a reproduction: https://github.com/DBTaylor/modbus-tcp-leak

It appears to be target agnostic. This issue sounds related, but it appears to have been fixed:
https://github.com/tokio-rs/tokio-proto/issues/194

**Comment by flosse** [comment]
@DBTaylor Thanks for the example repo. I can reproduce the behavior on my machine.

I tried to build it with the current `tokio-proto` master but unfortunately it's still the same :(

**Comment by uklotzde** [comment]
I've prepared a quick fix:

https://github.com/slowtec/tokio-modbus/pull/34

```
[patch.crates-io]
tokio-modbus = { git = "https://github.com/uklotzde/tokio-modbus.git", branch = "tcp_disconnect" }
```

After invoking disconnect() the connections will enter TIME_WAIT and should disappear after ~30 seconds (depending on your config). Does this solve your issues?

**Comment by DBTaylor** [comment]
@uklotzde yep that works!

**Comment by uklotzde** [comment]
Great, I will prepare a release.

Your example with the testing instructions was a great help to quickly solve this bug!
